name: Build and Push Ansible Execution Environment

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Add permissions for packages
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible Builder
        run: pip install ansible-builder>=3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Execution Environment
        run: |
          ansible-builder build --container-runtime docker -t ghcr.io/${{ github.repository_owner }}/ansible-runner:latest
          
          # Make the package public (optional - remove if you want it private)
          docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/ansible-runner:latest
          
          # Push to registry
          docker push ghcr.io/${{ github.repository_owner }}/ansible-runner:latest