name: Build and Push Ansible Execution Environment

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible Builder
        run: pip install ansible-builder>=3.0.0

      - name: Generate unique tag
        id: tag
        run: |
          # Generate a timestamp tag
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "Generated unique tag: $TIMESTAMP"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Execution Environment
        run: |
          # Build with both latest and timestamp tags
          ansible-builder build --container-runtime docker \
            -t ghcr.io/${{ github.repository_owner }}/ansible-runner:latest \
            -t ghcr.io/${{ github.repository_owner }}/ansible-runner:${{ env.TIMESTAMP }}

      - name: Push to GitHub Container Registry
        run: |
          # Push both tags to registry
          docker push ghcr.io/${{ github.repository_owner }}/ansible-runner:latest
          docker push ghcr.io/${{ github.repository_owner }}/ansible-runner:${{ env.TIMESTAMP }}
          
          # Output the image details for reference
          echo "Image pushed with tags:"
          echo "  - ghcr.io/${{ github.repository_owner }}/ansible-runner:latest"
          echo "  - ghcr.io/${{ github.repository_owner }}/ansible-runner:${{ env.TIMESTAMP }}"
          
          # Set output for use in other jobs or for reference
          echo "IMAGE_TAG=${{ env.TIMESTAMP }}" >> $GITHUB_OUTPUT

      - name: Display Image Tag
        run: |
          echo "=================================================="
          echo "New image available at:"
          echo "ghcr.io/${{ github.repository_owner }}/ansible-runner:${{ env.TIMESTAMP }}"
          echo "=================================================="
          echo "Update your Kubernetes deployment to use this tag"
          echo "and set imagePullPolicy: Always"